# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    # This is migrated to https://github.com/javaxcel/javaxcel.
    # branches:
    # - release
    
  # This is migrated to https://github.com/javaxcel/javaxcel.
  # schedule:
  # - cron: "0 20 * * 6" # Runs at 05:00 Asia/Seoul on Sun.

jobs:
  build:
    name: Builds with java ${{ matrix.java }} on ${{ matrix.os }}
       
    strategy:
      fail-fast: true
      max-parallel: 3 # Maximum: Sum of matrices.
      matrix:
        java: [8, 8.0.232, 11, 11.0.4, 17] # LTS versions (latest and fixed).
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
         
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: "zulu"
        cache: "maven"
        
    - name: Build with Maven
      run: mvn clean package -B --file pom.xml
      
    - name: Send code coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        # Not required for public repository.
        # token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
